"""delete nickname

Revision ID: 03e086c615d1
Revises: 7a4a0d4dc7a5
Create Date: 2025-06-16 23:05:31.073539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03e086c615d1'
down_revision = '7a4a0d4dc7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.drop_index('nickname')
        batch_op.drop_column('nickname')
        batch_op.drop_column('create_at')
        batch_op.drop_column('code_expiration')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('code_expiration', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_index('nickname', ['nickname'], unique=True)
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
