"""add email verification fields

Revision ID: 7a4a0d4dc7a5
Revises: 9bbf919fecb9
Create Date: 2025-06-15 12:51:52.150175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4a0d4dc7a5'
down_revision = '9bbf919fecb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('code_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('create_at')
        batch_op.drop_column('code_expiration')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
